apiVersion: apps/v1
kind: Deployment
metadata:
  name: prod-intima-fooocus-deployment
  namespace: prod-intima-fooocus
  labels:
    app: prod-intima-fooocus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prod-intima-fooocus
  template:
    metadata:
      labels:
        app: prod-intima-fooocus
    spec:
      containers:
        - name: prod-intima-fooocus
          image: corentin35/intima-fooocus:${TAG_VERSION}
          imagePullPolicy: Always
          ports:
            - containerPort: 7865
          env:
            - name: CMDARGS
              value: "--listen"
            - name: DATADIR
              value: "/content/data"
            - name: config_path
              value: "/content/data/config.txt"
            - name: config_example_path
              value: "/content/data/config_modification_tutorial.txt"
            - name: path_checkpoints
              value: "/content/data/models/checkpoints/"
            - name: path_loras
              value: "/content/data/models/loras/"
            - name: path_embeddings
              value: "/content/data/models/embeddings/"
            - name: path_vae_approx
              value: "/content/data/models/vae_approx/"
            - name: path_upscale_models
              value: "/content/data/models/upscale_models/"
            - name: path_inpaint
              value: "/content/data/models/inpaint/"
            - name: path_controlnet
              value: "/content/data/models/controlnet/"
            - name: path_clip_vision
              value: "/content/data/models/clip_vision/"
            - name: path_fooocus_expansion
              value: "/content/data/models/prompt_expansion/fooocus_expansion/"
            - name: path_outputs
              value: "/content/app/outputs/"
          volumeMounts:
            - name: fooocus-data
              mountPath: /content/data
      volumes:
        - name: fooocus-data
          persistentVolumeClaim:
            claimName: fooocus-pvc
      imagePullSecrets:
        - name: regcred
