apiVersion: v1
kind: Secret
metadata:
  name: regcred
  namespace: prod-intima-fooocus
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CiAgICAgICJ1c2VybmFtZSI6ICJjb3JlbnRpbjM1IiwKICAgICAgInBhc3N3b3JkIjogImRja3JfcGF0X1N3bU1sTV9Od2dNTWJodjlfRFZNMUVWNVZRTSIsCiAgICAgICJlbWFpbCI6ICJjb3JlbnRpbmRldnByb0Bob3RtYWlsLmNvbSIKICAgIH0KICB9Cn0=
