apiVersion: v1
kind: PersistentVolume
metadata:
  name: prod-intima-fooocus-pv
  namespace: prod-intima-fooocus
  labels:
    app: prod-intima-fooocus
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5000Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/prod"
