name: deploy_cluster_production

on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  build_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout this repository
        uses: actions/checkout@v4

      - name: Clone Fooocus repository
        run: |
          git clone https://github.com/lllyasviel/Fooocus.git
        working-directory: .

      - name: Get latest release tag
        id: previoustag
        uses: WyriHaximus/github-action-get-previous-tag@v1

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker image - Production version latest
        uses: docker/build-push-action@v6
        with:
          context: ./Fooocus  # Construire l'image à partir du dépôt Fooocus cloné
          file: ./Fooocus/Dockerfile
          push: true
          tags: corentin35/fooocus:latest

      - name: Build and push Docker image - Production version x.x.x
        uses: docker/build-push-action@v6
        with:
          context: ./Fooocus
          file: ./Fooocus/Dockerfile
          push: true
          tags: corentin35/fooocus:${{ steps.previoustag.outputs.tag }}

      - name: Replace image tag in deployment.yaml for Kubernetes
        run: |
          sed -i 's/\${TAG_VERSION}/'${{ steps.previoustag.outputs.tag }}'/g' k8s/production/deployment.yaml

      - name: Connect to the cluster K3S for deploy
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBECONFIG }}
        with:
          args: |
            apply -f k8s/production/namespace.yaml
            -f k8s/production/certificate.yaml
            -f k8s/production/docker-registry-secret.yaml 
            -f k8s/production/deployment.yaml
            -f k8s/production/ingress.yaml 
            -f k8s/production/service.yaml
            -f k8s/production/pv.yaml
            -f k8s/production/pvc.yaml
